name: 'cdk-action-for-python-projects'
description: 'Action for running CDK and build layer for python projects in amazonlinux 2'
working_dir:
    description: 'AWS CDK working directory.'
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload-cloud'
  color: 'yellow'
inputs:
  python_build_command:
    description: 'command to build your layer'
    default: 'python -V'
  cdk_command:
    description: 'CDK Command'
    default: 'cdk --version'
  working_dir:
    description: 'AWS CDK working directory.'
    default: '.'
